### ISSUE TITLE
個人アクセストークンの種類について注意を促す

### ISSUE THREAD

**Issue by michiharu** [kayu-s/supergirl#19]
現在は個人アクセストークン未設定や認証エラーが発生した場合、次の文言が表示されます。
> GitHubで取得した個人アクセストークンを入力してください。権限は「repo」のみで大丈夫です。

現在は個人アクセストークンについて、新しい種類が登場しています。
![image](https://user-images.githubusercontent.com/2579373/218290204-86b1c9f7-a5f8-443b-891f-00793d780bcf.png)

[公式ドキュメント](https://docs.github.com/ja/graphql/guides/forming-calls-with-graphql#graphql%E3%81%A7%E3%81%AE%E8%AA%8D%E8%A8%BC)によるとGraphql APIはこの新しいトークンを使用した認証は出来ません。

Rest API は対応しているためオプションページでリポジトリ一覧が表示されるのですが、ポップアップ内部でエラーが発生し、混乱を招くと思います。

ポップアップ側でのエラーやオプション画面で、個人アクセストークンの種類について言及することでユーザーに分かりやすいUXになると思いました。

**Comment by michiharu** [comment]
追加情報です。Tokens (classic)でも『権限は「repo」のみで大丈夫です。』ではありませんでした。

repoのみの場合、以下のエラーが発生し、`read:org`, `read:discussion`を追加したトークンの場合にエラーは解消しました。
> Error: Your token has not been granted the required scopes to execute this query. The 'name' field requires one of the following scopes: ['read:org', 'read:discussion'], but your token has only been granted the: ['repo'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.

対応としては２つ考えられます。
- `read:org`, `read:discussion`のスコープ追加を促すよう文言を修正する
- コメント通知のON/OFFによって、queryを使い分ける
  - トークンのスコープを確かめる専用のAPIは無いようですが、401のエラーメッセージから`read:org`や`read:discussion`が足りていないことは判別可能であるため、トークンを設定するタイミングでスコープを確認・保存し、コメント通知のトグルUIの活性／非活性と連動させる

このツールのユーザーがエンジニアである点を考えれば、そこまで`read:org`, `read:discussion`を追加することに抵抗はないと思います。そのため前者の対応が良さそうですが、いかがでしょうか？

**Comment by kayu-s** [comment]
起票ありがとうございます。
実は権限の説明が実態に即していない件は修正はしていましたが、リリースしていない状態でした！
https://github.com/kayu-s/supergirl/commit/1a690f40503544064a3e46cf33dcf6cfdfd40c86

トークンの種類についての説明追加と合わせて、パッチリリースするのが良いかと思いました。

**Comment by michiharu** [comment]
最新ソースでの確認が漏れており失礼しました。

トークンを作成するところで`(classic)`と表記されるので、このアプリの案内も`(classic)`を付け加えた方がわかりやすくなりそうですね。

本件の今後の流れ、理解しました。リリース作業などと一緒に作業されるかと思いますので本件Issueを閉じるタイミングなどお任せします。改めてレスポンスありがとうございました。
